# Generated by Django 4.2.5 on 2023-09-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_adminuser_first_name_alter_adminuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='adminuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
