# Generated by Django 4.2.5 on 2023-09-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_doctor_first_name_en_and_more'),
        ('users', '0006_alter_adminuser_options_alter_adminuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.workplace'),
        ),
    ]
