# Generated by Django 4.2.5 on 2023-09-26 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_adminuser_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqamini to'g'ri ko'rsating, masalan: +998901234567", regex='^\\+998\\d{9}$')]),
        ),
    ]
