# Generated by Django 4.2.5 on 2023-09-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_username_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
