# Generated by Django 4.2.5 on 2023-09-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('start_working', models.TimeField(default='09:00')),
                ('end_working', models.TimeField()),
            ],
        ),
    ]
