# Generated by Django 4.2.5 on 2023-09-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_specialty_workplace_remove_doctor_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
