# Generated by Django 4.2.5 on 2023-09-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_doctor_first_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('at_work', 'at work'), ('not_at_work', 'not at work')], default='at_work', max_length=32),
        ),
    ]
