# Generated by Django 4.2.5 on 2023-09-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_doctor_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
